### ISSUE TITLE
Wo speichern wir Anleitungen etc.?

### ISSUE THREAD

**Issue by cytosin12** [tobjaw/distillation-automation#21]
Ueberlegen, wo Anleitungen fuer alles moegliche am sinnvollesten gespeichert werden koennen. Vielleicht direkt bei Github und einer einfachen .txt-Datei?

**Comment by tobjaw** [comment]
würde ich direkt hier im repo speichern
bevorzugt in der `README.md`, die wird auch in der doc automatisch eingebunden  
als format bietet sich markdown an, das wird von GitHub automatisch formatiert u. von Doxygen unterstützt :)

**Comment by cytosin12** [comment]
Jo, klingt gut!
